sonar.projectKey=magic8
sonar.projectName=Magic8 Canvas Card Game Engine
sonar.projectVersion=0.9.0

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js
sonar.exclusions=node_modules/**,coverage/**
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
